version: '{build}'
image: Visual Studio 2019
configuration:
- Release
platform: x64
build:
  project: source-code/PD-Loader.sln
  verbosity: minimal
after_build:
- cmd: >-
    md %TMP%\full\

    md %TMP%\full\patches\

    md %TMP%\full\plugins\
    
    md %TMP%\full\ram\

    md %TMP%\full\ram\databank_template\
   
    md %TMP%\amd-pack\
    
    md %TMP%\amd-pack\plugins\
    
    md %TMP%\amd-pack\amd-tools\
    
    md "%TMP%\amd-pack\amd-tools\ARB Patcher Source"
    
    md "%TMP%\amd-pack\amd-tools\ARB Patcher Source\gamesettings"



    copy %APPVEYOR_BUILD_FOLDER%\source-code\x64\%CONFIGURATION%\dnsapi.dll %TMP%\full\
    
    copy %APPVEYOR_BUILD_FOLDER%\source-code\x64\%CONFIGURATION%\*.dva %TMP%\full\plugins\
    
    del %TMP%\full\plugins\Novidia.dva

    copy "%APPVEYOR_BUILD_FOLDER%\source-code\data\README - PD Loader.url" %TMP%\full\

    copy %APPVEYOR_BUILD_FOLDER%\source-code\data\verify_base_game.sfv %TMP%\full\

    copy %APPVEYOR_BUILD_FOLDER%\source-code\data\verify_base_game.md5 %TMP%\full\

    copy %APPVEYOR_BUILD_FOLDER%\source-code\data\verify_mount_data.sfv %TMP%\full\

    copy %APPVEYOR_BUILD_FOLDER%\source-code\data\verify_mount_data.md5 %TMP%\full\

    copy %APPVEYOR_BUILD_FOLDER%\source-code\data\glut32.dll %TMP%\full\

    copy %APPVEYOR_BUILD_FOLDER%\source-code\data\plugins\*.* %TMP%\full\plugins\
    
    copy %APPVEYOR_BUILD_FOLDER%\source-code\data\ram\databank_template\*.dat %TMP%\full\ram\databank_template\

    copy %APPVEYOR_BUILD_FOLDER%\source-code\data\patches\custom_freeplay_text_example.p %TMP%\full\patches\
    
    copy %APPVEYOR_BUILD_FOLDER%\source-code\x64\%CONFIGURATION%\Novidia.dva %TMP%\amd-pack\plugins\
    
    copy %APPVEYOR_BUILD_FOLDER%\source-code\data\amd-tools\*.*  %TMP%\amd-pack\amd-tools\
    
    copy "%APPVEYOR_BUILD_FOLDER%\source-code\data\amd-tools\ARB Patcher Source\*.*"  "%TMP%\amd-pack\amd-tools\ARB Patcher Source\"
    
    copy "%APPVEYOR_BUILD_FOLDER%\source-code\data\amd-tools\ARB Patcher Source\gamesettings\*.*"  "%TMP%\amd-pack\amd-tools\ARB Patcher Source\gamesettings\"

    

    cd %TMP%\full\

    7z a %APPVEYOR_BUILD_FOLDER%\PD-Loader-%CONFIGURATION%-AppVeyor.zip *
  
    cd %TMP%\amd-pack\amd-tools\
    
    C:\Python38\python.exe -m pip install cx_freeze
    
    C:\Python38\Scripts\cxfreeze.exe "ARB Patcher Source\main.py" --target-dir "ARB Patcher"
    
    mkdir "ARB Patcher\gamesettings"
    
    copy "ARB Patcher Source\gamesettings\*.*" "ARB Patcher\gamesettings\"
    
    del /Q "ARB Patcher Source\gamesettings"
    
    rmdir "ARB Patcher Source\gamesettings"
    
    del /Q "ARB Patcher Source"
    
    rmdir "ARB Patcher Source"
    
    del "patch shaders py.bat"
    
    cd ..
    
    move amd-tools\README.txt AMD-README.txt
    
    7z a %APPVEYOR_BUILD_FOLDER%\PD-Loader-%CONFIGURATION%-AMDPack-AppVeyor.zip *


artifacts:
- path: PD-Loader-*.zip
